#!/bin/bash
####### User to edit these accordingly ######
export MATLAB_PATH=/home/andrew/Matlab_R2012b
PLATFORM=lin64
export XILINX_PATH=/home/andrew/Xilinx/14.7/ISE_DS
export MLIB_DEVEL_PATH=/home/andrew/Github/mlib_devel
#############################################
source $XILINX_PATH/settings64.sh
export PATH=${PATH}:${XILINX}/ISE/bin/${PLATFORM}:${XILINX_PATH}/ISE/sysgen/bin/${PLATFORM}
export XPS_BASE_PATH=$MLIB_DEVEL_PATH/xps_base
export MATLAB=$MATLAB_PATH
$MATLAB/bin/matlab
